DROP TABLE IF EXISTS BOOK;

CREATE TABLE BOOK(
SERIALNUMBER SERIAL PRIMARY KEY NOT NULL,
TITLE VARCHAR(100) NOT NULL,
AUTHOR VARCHAR(100) NOT NULL,
DATE DATE DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO BOOK(TITLE,AUTHOR,DATE) VALUES('Adventures of Sherlock Holmes','Sir Arthur Conan Doyle',NOW());
INSERT INTO BOOK(TITLE,AUTHOR,DATE) VALUES('Adventures of Tom Sawyer, The','Mark Twain',NOW());
INSERT INTO BOOK(TITLE,AUTHOR,DATE) VALUES('Ain-i-Akbari','Abul Fazal',NOW());
INSERT INTO BOOK(TITLE,AUTHOR,DATE) VALUES('Alchemist, The','Paulo Coelho',NOW());